services:
  redis:
    image: 'redis:6-alpine'
    ports:
      - '6379:6379'
    environment:
      TZ: Asia/Singapore
  database:
    image: postgres
    volumes:
      - /var/lib/postgresql/data
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: traffic
